name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: windows-latest #ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies and train model
        working-directory: ./MLOps/9_cicd
        run: |
          pip install -r ./MLOps/9_cicd/requirements.txt
          python ./MLOps/9_cicd/train_model.py

      - name: Build Docker image
        run: docker build -f Dockerfile -t 40days/iris-model .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to DockerHub
        run: docker push 40days/iris-model
